project_id = "zgmhbywdbikkzuvqfgpg"

[functions.ai-suggestions]
verify_jwt = false

[functions.generate-faq]
verify_jwt = false

[functions.explore-topic]
verify_jwt = false

[functions.ai-chat]
verify_jwt = true

[functions.discover-attractions]
verify_jwt = false

[functions.organize-itinerary]
verify_jwt = true
